1) numpy : C 언어 기반으로 구현된 고성능 다차원 배열(ndarray) 라이브러리.
- 반복문 없이도 벡터/행렬 연산 가능 → 연산 속도가 Python 내장 리스트보다 훨씬 빠름.
- 용도: 대수 계산, 수치 계산, 행렬 연산, 통계 계산.
- 결과 구조: ndarray (차원 수에 따라 1D, 2D, 3D 등 가능).

2) numpy 설치
- 쥬피터 노트북 코드 셀에서 !pip install numpy
- 또는 vscode 터미널에서 pip install numpy
- numpy는 커널 단위로 설치되므로, 타 ipynb 파일이더라도 커널 공유 시 바로 numpy 사용 가능

3) numpy 배열 특징
- 배열 내부의, 각 원소는 동일한 자료형으로만 구성된다.
- 배열 내부에 다른 자료형 데이터를 삽입하면, 표현범위가 더 큰 한가지 데이터 타입으로 자동 형변환된다.


### 번호 제목

"""
- 설명 1
- 설명 2
"""


#```


코드 작성란


#```


In [ ]:
### 7.2 Numpy 기본 배열 생성

"""
- numpy.array(리스트)
"""

"""
```
"""
import numpy as np
print(np.__version__) # Numpy 버전

list1 = [1,2,3,4,5,6,7,8,9,10]  # 파이썬 1차원 리스트
nArr1 = np.array(list1)         # 넘파이 배열로 변환
print(nArr1)                    # 공백으로 구분됨.
print('=' * 30)

list2 = [[1,2,3], [4,5,6], [7,8,9]] # 파이선 2차원 리스트
nArr2 = np.array(list2)
print(nArr2)
print('=' * 30)

list3 = [[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]] # 파이선 3차원 리스트
nArr3 = np.array(list3)
print(nArr3)
print('=' * 30)

"""
```
"""

2.3.3
[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


'\n```\n'

In [34]:
### 7.3 배열  자료형 확인 (dtype)

"""
- 배열.dtype : 배열 자료형을 출력
- numpy.array(리스트, dtype=자료형) : 배열 변환 시, 자료형을 지정할 수 있다.
"""

"""
```
"""
import numpy as np

nArr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(nArr1.dtype)          #int64
print('=' * 30)

nArr2 = np.array([1.1, 2.2, 3.3, 4.4])
print(nArr2.dtype)          #float64
print('=' * 30)

# 여러 자료형 동일 배열에 삽입 시, 표현 범위가 더 큰 자료형으로 자동 형변환 됨.
nArr3 = np.array([1, 2, 3.0, 4.0, 5.0])
print(nArr3)                #전부 float형으로 자동 변환됨
print(nArr3.dtype)          #float64
print('=' * 30)

# 배열 변환 시, dtype 속성을 이용해 데이터 타입을 지정할 수 있다.
nArr4 = np.array([1, 2, 3.0, 4.0, 5.0], dtype='int64')
print(nArr4)                #전부 int형
print(nArr4.dtype)          #int64
print('=' * 30)

# 또는 astype를 활용해 이미 생성된 배열의 자료형을 변경할 수 있다.
nArr4 = nArr4.astype(np.float64)
print(nArr4)                
print(nArr4.dtype)          #float64

"""
```
"""

int64
float64
[1. 2. 3. 4. 5.]
float64
[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64


'\n```\n'

In [ ]:
### 7.4 배열의 차원과 행,열 (ndim, shap, reshape)

"""
- 배열.ndim : 배열의 차원을 출력 1차원 => 1, 2차원 => 2, 3차원 => 3..
- 배열.shape : 배열의 행,열 관계를 출력. 
- 배열.reshape(행, 열) : 행,열 변환. 행에 음수 작성 시, 자동으로 연산에 의해 행의 갯수가 정해진다. 열도 마찬가지
"""

"""
```
"""
import numpy as np

nArr1 = np.array([1,2,3,4,5])
print(nArr1.ndim)   # 1     : 1차원
print(nArr1.shape)  # (5,)  : 1차원일 경우 행열이 다음과 같이 표시됨.
print('=' * 30)

nArr2 = np.array([[1,2,3],[4,5,6]])
print(nArr2.ndim)   # 2     : 2차원
print(nArr2.shape)  # (2,3) : 2행 3열
print('=' * 30)

nArr3 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(nArr3.ndim)   # 2      : 2차원
print(nArr3.shape)  # (3,4)  : 3행 4열
print('=' * 30)

nArr3 = nArr3.reshape(-1, 3) # 행열 변환. 3열에 맞춰 행의 갯수가 정해진다.
print(nArr3.shape)  # (4,3)  : 4행 3열
print('=' * 30)

nArr3 = nArr3.reshape(2, -1, 3) # 2행 3열로 변환하고, 깊이는 갯수에 맞춰.
print(nArr3)
print(nArr3.ndim)   # 3       : 3차원
print(nArr3.shape)  # (2,2,3) : 2행 2깊이 3열
print('=' * 30)

"""
```
"""

1
(5,)
2
(2, 3)
2
(3, 4)
(4, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


'\n```\n'

In [ ]:
### 7.5 배열 사칙연산

"""
- 배열 연산자 배열 : 배열간의 연산 시, 동일 인덱스 원소끼리 연산을 진행한다.
- &, | : 배열의 동일 인덱스 원소의 Boolean 값을 연산한다.
"""

"""
```
"""
import numpy as np

aList = np.array([1,2,3,4,5])
bList = np.array([6,7,8,9,10])

# 1은 6과, 2는 7과, 3은 8과, 4는 9와, 5는 10과 연산(동일 인덱스 원소끼리 연산 진행)
print(aList + bList)
print(aList - bList)
print(aList * bList)
print(aList / bList)
print('=' * 30)

# 배열과 숫자 연산 시, 배열의 모든 원소에 숫자를 연산한다.
print(aList + 3)
print(aList - 1)
print(aList * 2)
print(aList / 2)
print('=' * 30)

# 간단 문제
aList = np.array([1,2,3])
bList = np.array([10,20,30])

print(2 * aList + bList)
print(aList == 2)
print(bList > 10)
print((aList == 2) & (bList > 10))

"""
```
"""

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[4 5 6 7 8]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


'\n```\n'

In [10]:
### 7.6 배열 인덱스 슬라이싱

"""
- 파이썬 리스트와 다르게, 배열 슬라이스는 원래 배열에 대한 View이기 때문에, 값 변경 시 원본 배열에도 영향이 있다.
- 원본 배열에 영향이 없도록 하고자 copy() 메서드를 사용해 깊은 복사를 진행할 수 있다.
- 다차원 배열에서 특정 값을 추출하는것을 인덱스 슬라이싱을 이용할 수 있고, 파이썬 리스트에서의 추출과 동일하다.

"""

"""
```
"""
import numpy as np

# 파이썬 리스트 인덱스 슬라이싱
aList = [[0,1,2], [3,4,5]]
print(aList[0][0], aList[0][1], aList[1][2]) # 0, 1, 5 추출

print(aList[0][:2], aList[1][1:]) # 0,1과 4,5 추출
bList = np.array([aList[0][1], aList[1][1]]) # 1,4 추출하여 리스트의 원소로 만든 후, 넘파이 배열로 변환
print(bList)

print('=' * 30)

# 주의!
cList = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(cList[1:, 1:])    # [[5,6], [8,9]
print(cList[1:][1:])    # [[7,8,9]]
print('=' * 30)

#문제 1 cList에서 값 5만 추출하시오.
print(cList[1][1])
print(cList[1, [1]])
#문제 2 cList에서 **첫 번째 행 전체 ([1,2,3])**를 추출하시오.
print(cList[0])
#문제 3 cList에서 **마지막 열 ([3,6,9])**만 추출하시오.
print(cList[:, -1])
#문제 4 cList에서 왼쪽 위 2×2 부분 배열 (즉, [[1,2],[4,5]])을 추출하시오.
print(cList[:2, :2])
#문제 5 cList에서 **대각선 값 ([1,5,9])**을 추출하시오.
print(cList[[0,1,2],[0,1,2]])
#문제 6 cList에서 6, 9만 출력하시오.
print(cList[1:, -1])

print('=' * 30)

dList = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
print(dList)
print(dList[:, :2])
print(dList[[0,1,2,3],[0,0,0,0]])

"""
```
"""

0 1 5
[0, 1] [4, 5]
[1 4]
[[5 6]
 [8 9]]
[[7 8 9]]
5
[5]
[1 2 3]
[3 6 9]
[[1 2]
 [4 5]]
[1 5 9]
[6 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[ 0  4  8 12]


'\n```\n'

In [ ]:
### 7.7 fancy indexing

"""
- 대괄호안의 인덱스 정보로, 숫자나 슬라이스가 아니라, 위치정보를 나타내는 또 다른 ndarray 배열을 받을 수 있다.
- 불리언(Boolean) 배열 방식과 정수 배열 방식
"""

"""
```
"""
import numpy as np

# 1차원 배열 fancy 인덱싱
a = np.array([0,1,2,3,4,5,6,7,8,9])

# 1차원 배열에서 Boolean 인덱싱 (배열과 인덱싱 배열의 길이가 같아야 함.)
idx = np.array([True, False, True, False, True, False, True, False, True, False]) # Boolean 배열의 길이가 a 길이랑 다르면 오류
print(a[idx]) # True인 인덱스만 추출
print(a[a % 2 != 0]) # 각 원소에 조건식 적용하여, 홀수 데이터만 추출
print('=' * 30)

# 1차원 배열에서 정수 인덱싱 (배열과 인덱싱 배열의 길이가 달라도 괜찮음)
  # 다만 인덱싱 배열의 원소(원본 배열 인덱스를 가리킴)가 원본 배열의 인덱스를 넘어가면 오류.
idx = np.array([0,0,1,1,2,2]) # 0번 인덱스, 0번 인덱스, 1번 인덱스, 1번 인덱스, 2번 인덱스, 2번 인덱스
print(a[idx])  # 0 0 1 1 2 2
print('=' * 30)

# 2차원 배열 정수 인덱싱
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a[:, [0,3]]) # 모든행, [0번열, 3번열]
print(a[:, [True, False, False, True]])
print('=' * 30)

# 행 순서 변경하기
print(a[[2, 0, 1]])
# 열 순서 변경하기
print(a[:, [2, 0, 1, 3]])
print('=' * 30)

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
# 3의 배수
print(x[x % 3 == 0])
# 4로 나누면 1이 남는 수
print(x[x % 4 == 1])
# 3으로 나누면 나누어지고, 4로 나누면 1이 남는 수
print(x[(x % 3 == 0) & (x % 4 == 1)]) # 조건식 2개 이상 작성 시, ()로 묶어 작성
print('=' * 30)

"""
```
"""

[0 2 4 6 8]
[1 3 5 7 9]
[0 0 1 1 2 2]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 3  1  2  4]
 [ 7  5  6  8]
 [11  9 10 12]]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


'\n```\n'

In [143]:
import numpy as np

names = np.array(['a', 'b', 'c', 'd', 'a', 'b', 'd'])
boolArr = [names == 'a']
print(boolArr)

numArr = np.array([1,2,3,4,5,6,7])
print(numArr[numArr % 2 == 0])

numArr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


[array([ True, False, False, False,  True, False, False])]
[2 4 6]


In [ ]:
### Numpy 함수

"""
- 설명 1
"""

"""
```
"""
import numpy as np

data = [1,4,9,16]

print(np.sum(data))
print(np.sqrt(data))
print(np.pow(data))
print(np.mean(data))
print(np.abs(data))

"""
```
"""