In [ ]:
### arange 실습

import numpy as np

# 0 ~ 99까지
l1 = np.arange(100)
print(l1)

# 구구단 3단 출력
l2 = np.arange(1, 10) * 3
print(l2)

# 0부터 1까지 0.1 간격
l3 = np.arange(0, 1, 0.1)
print(l3)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 3  6  9 12 15 18 21 24 27]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[0 1 2]
 [3 4 5]]


In [ ]:
### reshape 실습

import numpy as np

# 행, 열 변환
l1 = np.array([0,1,2,3,4,5])
print(l1.reshape(2,3))

# 3행 1열로 변환
l2 = np.arange(3)
print(l2.reshape(3, 1)) 
print(l2.reshape(-1, 1))  # 1열로 만들고 행(음수)은 자동 처리


[[0 1 2]
 [3 4 5]]
[[0]
 [1]
 [2]]
[[0]
 [1]
 [2]]


In [ ]:
### ones 실습

import numpy as np

# 1이 20개 저장된 배열
li1 = np.ones(20)
print(li1)

# 1로 채워진 4행 5열
li2 = np.ones(20).reshape(4,5)
print(li2)

# 255로 채워진 10행 10열
li3 = (np.ones(100) * 255).reshape(10, 10)
print(li3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


In [25]:
### zeros 실습

import numpy as np

li1 = np.zeros(12).reshape(3,4)
print(li1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
### dtype 실습

import numpy as np

# 리스트를 정수형 배열로 변환
l = [1,2,3]
l1 = np.array(l, dtype='int32')
print(l1)

# 데이터 타입 확인
print(l1.dtype)

# 데이터 타입 변경
l1 = l1.astype('int16')
print(l1.dtype)



[1 2 3]
int32
int16
100.0


In [ ]:
### 인덱싱 실습

import numpy as np

arr = np.arange(9).reshape(3,3)
print(arr)

# 마지막 행만 출력
print(arr[-1:])
print(arr[2:])

# 두번째 컬럼만 출력
print(arr[:, 1])
print(arr[:, -2])

# 0~24까지의 5행 5열
arr = np.arange(25).reshape(5,5)
print(arr)

# 17 출력
print(arr[3][2])

# 17,18,19 22,23,24 출력
print(arr[3:,2:])

# 대각선 뽑기
print(arr[[0,1,2,3,4],[0,1,2,3,4]])

# (2행4열, 4행 4열)
print(arr[[2,4], 4])



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]]
[[6 7 8]]
[1 4 7]
[1 4 7]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
17
[[17 18 19]
 [22 23 24]]
[ 0  6 12 18 24]
[14 24]


In [ ]:
### 슬라이싱 실습

import numpy as np

arr = np.arange(5)

# [1 3] 추출
print(arr[[1,3]])

arr = np.arange(25).reshape(5,5)
print(arr)

# [6 7 8 9] 추출
print(arr[1,1:])
print(arr[[1],[1,2,3,4]])

# [11 12 16 17] 추출
print(arr[2:4, 1:3])

# 첫번째, 두번쨰 컬럼 추출
print(arr[:, [0,1]])

# 6,7,11,12 2행 2열로 추출
print(arr[1:3, 1:3])


[1 3]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[6 7 8 9]
[6 7 8 9]
[[11 12]
 [16 17]]
[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
[[ 6  7]
 [11 12]]
[ 0 23]


In [ ]:
### 연산

import numpy as np

arr = np.arange(1,4)
print(arr)

# 각 원소에 10을 곱하라
arr *= 10
print(arr)

# 각 원소 제곱 결과 출력
arr = np.arange(1,4)
arr **= 2
print(arr)

# 과목별 평균 점수
arr = np.array([[10,20], [14,16]]) # [국어, 영어], [국어, 영어]
print(arr.mean(axis=1)) # 수직 축

# 행렬 곱
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(1,5).reshape(2,2)

print(arr1 * arr2)



[1 2 3]
[10 20 30]
[1 4 9]
[15. 15.]
[[ 0  2]
 [ 6 12]]


In [ ]:
### 전치행렬, 짝수, 홀수 배열
import numpy as np

# 전치 행렬
arr = np.arange(9).reshape(3, 3)
print(arr)
print(arr.T)

arr = np.arange(10)

# 짝수
print(arr[arr % 2 == 0])
# 홀수
print(arr[arr % 2 == 1])
# 3보다 크고 7보다 작은 수 출력
print(arr[(arr>3) & (arr<7)])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[0 2 4 6 8]
[1 3 5 7 9]
[4 5 6]


In [ ]:
### 조건에 따라 값 출력 or 변경

import numpy as np

arr = np.array([-1, 2, -3, 4])

# 음수만 출력
print(arr[arr < 0])

# 음수 => 0으로 치환
arr[arr < 0] = 0
print(arr)

# 음수 => 양수로 변환
arr = np.array([-1, 2, -3, 4])
arr[arr < 0] -= arr[arr < 0] * 2
print(arr)

[-1 -3]
[0 2 0 4]
[1 2 3 4]


In [128]:
### 무작위로 섞기, 최댓값, 최솟값, 정렬

import numpy as np

arr = np.arange(1,6)

# 무작위로 섞기
np.random.shuffle(arr)
print(arr)


# 최댓값의 인덱스 번호
print(arr.argmax())
# 최솟값의 인덱스 번호
print(arr.argmin())

# 오름차순 정렬
arr.sort()
print(arr)


[1 3 5 2 4]
2
0
[1 2 3 4 5]
